### ISSUE TITLE
加过喜欢的用户列表

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#10]
原版Pixiv上有查看加过喜欢的用户列表的功能，但是Pix-EzViewer上却没有。可以考虑加入吗？

![IMG_20200708_163828](https://user-images.githubusercontent.com/67962258/86897262-c1fb7400-c139-11ea-8424-c454fe3c99c4.jpg)
![Screenshot_2020-07-08-16-32-25-32_2b539382a401af58f8b13a32b77067ec](https://user-images.githubusercontent.com/67962258/86897271-c4f66480-c139-11ea-9b24-861dbb873f81.jpg)

**Comment by ultranity** [comment]
经你说过才发现有这种功能，但如果不是画师的话对这个没什么需求的样子？

我会加到TODO里的

**Comment by LZTSGS** [comment]
> 经你说过才发现有这种功能，但如果不是画师的话对这个没什么需求的样子？
> 
> 我会加到TODO里的



> 经你说过才发现有这种功能，但如果不是画师的话对这个没什么需求的样子？
> 
> 我会加到TODO里的

对一般人还是有点用的，在一个画师发布了一张高质量的图片的时候第一时间去看看谁收藏了这图，能第一时间收藏这些图片的一般都是藏图大佬，进去嫖他们的收藏夹可香了呢…………………………

**Comment by ultranity** [comment]
不会等太久，预计下个版本更新
