### ISSUE TITLE
一键下载

### ISSUE THREAD

**Issue by anosu** [ultranity/Pix-EzViewer#12]
能不能做个一键下载、收藏多张图片的功能？
用https://github.com/CeuiLiSA/Pixiv-Shaft          的一键下载图片功能挺方便的，但是他的自定义图片命名规则没有Pix-EzViewer好（能写入标签太香了），所以很纠结该用哪款来下图。

另外加入个识别手机里图片ID并批量重命名图片的功能（在另外一个帖子看的你们讨论了)的话也可以解决我的烦恼呢！能做的话建议做个。
![S00714-08093782](https://user-images.githubusercontent.com/60904693/87365685-70c00a00-c5a9-11ea-91f6-8462c30cc47d.jpg)

**Comment by ultranity** [comment]
也是计划中的功能，等等吧

**Comment by ultranity** [comment]
近期先使用收图模式吧，除非是全选已经基本等同于强制预览一遍的批量下载了
