### ISSUE TITLE
图片下载提示语

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#14]
图片下载时弹出的提示语可以不可以提供一个关闭的选项(或者换种提示方式)，很多时候它提示的速度跟不上下载图片的速度，这种时候它除了遮挡画面就基本没什么作用了，有的时候正好挡在翻译按钮和查看评论按钮时就更难受了……………
![IMG_20200715_005313](https://user-images.githubusercontent.com/67962258/87454095-18831980-c636-11ea-9e6f-778cba1f91ce.jpg)

还有就是我更新了最新版以后，时不时就会有几张图片加载不出来(我网络没问题)
![Screenshot_2020-07-15-01-09-01-63_79d0ff8f9752a3fc32487e6d62330a6a](https://user-images.githubusercontent.com/67962258/87455391-f4283c80-c637-11ea-9e84-b0778805ca05.jpg)
![Screenshot_2020-07-15-01-11-00-15_4b917d10dd463a191f2cd7bd0a2e90b5](https://user-images.githubusercontent.com/67962258/87455575-41a4a980-c638-11ea-88b1-8b307a345d0b.jpg)
![Screenshot_2020-07-15-01-11-31-11_4b917d10dd463a191f2cd7bd0a2e90b5](https://user-images.githubusercontent.com/67962258/87455589-4701f400-c638-11ea-98bc-80a313aa9d4e.jpg)

**Comment by ultranity** [comment]
也在之前就加在TODO里了，可以看看
[点此查看更新记录及TODO](https://github.com/ultranity/Pix-EzViewer/blob/master/ReleaseNote.md)

当然提issue可以鼓励我优先开发hhh
