### ISSUE TITLE
华为手机下载还是不行

### ISSUE THREAD

**Issue by Sevenholysins** [ultranity/Pix-EzViewer#16]
点save会闪退，点进去点下载会跳出来

**Comment by ultranity** [comment]
已尝试修复

**Comment by Sevenholysins** [comment]
十分感谢您的付出！



---原始邮件---
发件人: "elucida"<notifications@github.com&gt;
发送时间: 2020年7月15日(周三) 晚上11:13
收件人: "ultranity/Pix-EzViewer"<Pix-EzViewer@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Sevenholysins"<1342504467@qq.com&gt;;
主题: Re: [ultranity/Pix-EzViewer] 华为手机下载还是不行 (#16)




 
已尝试修复
