### ISSUE TITLE
图片排版

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#17]
图片排版可以提供一个单列显示略缩图的选项，这样主要可以空出更大的剩余空间来加入更多的功能按键(咕了很久的一键三连)之类的
双列排布可以追求简洁
单列排布可以追求显示更多的信息和提供更多的功能按键

**Comment by ultranity** [comment]
排版暂时不修改了，工作量太大，下个版本上线三连收图模式
