### ISSUE TITLE
把收藏夹放到一级菜单

### ISSUE THREAD

**Issue by xushet** [ultranity/Pix-EzViewer#19]
常用功能

**Comment by ultranity** [comment]
没get到你的点，具体描述

**Comment by xushet** [comment]
> 没get到你的点，具体描述

把收藏夹导航菜单

**Comment by ultranity** [comment]
没有好好描述实在是爱莫能助

**您的功能请求是否与某个问题相关？**
请清晰简洁的描述一下问题所在

**描述你想要的解决方案**
清晰而简洁的描述你想要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的任何备选解决方案或功能的清晰而简明的描述。

**附加**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
