### ISSUE TITLE
Improving the colors of certain icons

### ISSUE THREAD

**Issue by FrzMtrsprt** [ultranity/Pix-EzViewer#2]
Hi!
I noticed that in the picture detail page, the top bar icons are hard to see when the picture is mainly white. Is it possible to add a shadow on the top bar, so that the icons remain visible in such situation? Would be better if the icons change color dynamically with the picture's color.
![Screenshot_20200618-000111](https://user-images.githubusercontent.com/15852717/84921318-e776fe00-b0f6-11ea-98c3-2ad02db3bc05.png)
Another problem is that in the ranking page, the "calendar icon" on the tab bar doesn't seem to follow night mode, that it remains white when night mode is on. 
![Screenshot_20200617-235141](https://user-images.githubusercontent.com/15852717/84921143-abdc3400-b0f6-11ea-8d9b-188e8b0037ba.png)
At last, thanks for maintaining the app!

**Comment by ultranity** [comment]
Thanks for your feedback.
1.The display of pictures should be guaranteed first. It's an acceptable defect since these buttons have fixed position, but I am trying to find a better layout scheme to balance them.
2. The icon color will be corrected in next release.
