### ISSUE TITLE
画师作品页面添加“只显示已收藏图片”功能

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#20]
在画师作品页面添加一个   “只显示已收藏图片”   的功能选项。

**Comment by ultranity** [comment]
点右上菜单有惊喜

**Comment by LZTSGS** [comment]
> 点右上菜单有惊喜

不是只有隐藏已收藏图片选项???找不到只显示已收藏图片的 选项呢………………
![S00726-10244848](https://user-images.githubusercontent.com/67962258/88470065-867aeb00-cf2a-11ea-988c-5243d726f1a2.jpg)

**Comment by ultranity** [comment]
这个功能后续准备整合到画师作品页面筛选里，先咕咕一段~

**Comment by ultranity** [comment]
还是把整合咕了吧，下个版本更新，另外自己的收藏页面增加隐藏已下载功能（限于当前下载目录），另外有利用一个python脚本收集以前电脑上的下载记录（基于pyroaring），目前自用体验还行
