### ISSUE TITLE
状态栏颜色有问题

### ISSUE THREAD

**Issue by HSantu** [ultranity/Pix-EzViewer#23]
**问题描述**
状态栏颜色有问题

**如何复现**
进入应用即可

**正常&异常表现**
状态栏与主题色同色

**BugReport**

**环境说明**
**Smartphone (please complete the following information):**
 - Device: Redmi K20Pro
 - OS: Android 10
 - Version 1.6.3R

![Screenshot_20200803-123855](https://user-images.githubusercontent.com/23703054/89146663-fa4e7080-d586-11ea-906c-7d1816cfa1cb.png)

**Comment by ultranity** [comment]
上个版本做手势条沉浸适配的时候忽略了主题:sweat:, 下版本更新修复
