### ISSUE TITLE
Bugly 更换为 AppCenter

### ISSUE THREAD

**Issue by HSantu** [ultranity/Pix-EzViewer#24]
**您的功能请求是否与某个问题相关？**
请清晰简洁的描述一下问题所在
关于 Bugly 组件导致应用 Play 商店下架问题

**描述你想要的解决方案**
一个清晰而简洁的描述你想要发生的事情。
是否有可能将 Bugly 更换为微软的 [AppCenter](https://appcenter.ms) ，以便于重新上架 Play 商店？

**描述您考虑过的替代方案**
对您考虑过的任何备选解决方案或功能的清晰而简明的描述。

**附加**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by ultranity** [comment]
play商店有原作者维护的flutter版本，无意相争，后续可能考虑放在Fdroid上
