### ISSUE TITLE
滑动式pixivision展示滑到后面会闪退

### ISSUE THREAD

**Issue by kobayashikanata** [ultranity/Pix-EzViewer#26]
**问题描述**
滑动式pixivision展示滑到后面会闪退

**如何复现**
1. Click on '汉堡菜单'
2. Click on '应用设置'
3. Scroll down to '滑动式pixivision展示'
4. Confirm Checker ‘滑动式pixivision展示’ is checked
5. Next Action ‘重启应用’
6. Scroll end of right in ‘主页-插画-banner’ 
7. Error occurred ‘应用闪退’

**正常&异常表现**

**BugReport**

**环境说明**
**Smartphone (please complete the following information):**
 - Device: [e.g. XiaoMi 10]   Redmi K20Pro 
 - OS: [e.g. Android 10]       Android10
 - Version [e.g. 1.5.6R]        1.6.3R

**Comment by ultranity** [comment]
已知问题，已修复，下版本更新
