### ISSUE TITLE
剪贴板PID识别弹窗会多次重复弹出

### ISSUE THREAD

**Issue by BAKAOLC** [ultranity/Pix-EzViewer#29]
**问题描述**
剪贴板复制内容带有数字时会在主界面触发PID识别，并弹窗提醒，点击 “取消” 并前往其它界面后再次回到主界面仍然会触发识别并弹窗

**如何复现**
1. 复制一串数字
2. 在主界面的弹窗提醒中点击“取消”
3. 前往其它任意界面再返回
4. 弹窗提醒再次出现

**正常&异常表现**
正常的情况应该是和点击“识别错误”或“确定”一样，在重新复制内容前不再重复识别该剪贴板内容

软件版本：1.6.7R

**Comment by ultranity** [comment]
目前的识别错误一项就是用来中止识别的，没加反馈记录之类的东西（免得看到用户的剪贴板内容），取消 按钮保留为重新进入后再提醒，可能这个提示文本还有待优化，有建议的话可以提出来
