### ISSUE TITLE
Pixivision UX enhancement

### ISSUE THREAD

**Issue by takase1121** [ultranity/Pix-EzViewer#30]
**Describe the bug**
I wouldn't call this a bug actually, but I think it hinders the user experience.
In the homepage, there are recommendations from Pixivision.
Clicking on it redirects to Pixivision via a webview, that's fair enough.
However, clicking on any illustrations in Pixivision opens up Pixiv in the webview.
This is useless because I have no way of getting the link and to open it in PixEz.
It literally destroys the whole point of Pixivision integration. I'd rather open Pixivision on a real browser and copy the links to PixEz.

**To Reproduce**
1. Go to Main page
2. Click on the Pixivision recommendations on top of the page
3. Click on any illustration in the page.

**Expected behavior**
Image opens in PixEz.

**Screenshots**
![image](https://user-images.githubusercontent.com/20792268/92293844-3182b980-ef59-11ea-8106-f05ac8ea5d8e.png)
![image](https://user-images.githubusercontent.com/20792268/92293850-37789a80-ef59-11ea-8a72-3022b600cfa0.png)
![image](https://user-images.githubusercontent.com/20792268/92293853-3c3d4e80-ef59-11ea-9420-fd59ca1ae7c6.png)

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 9 (MIUI 11)
 - Version: 1.6.7R

**Proposed way to solving this**
Detect URL changes of the webview.
If it changes to `https://pixiv.net` or something similiar, intercept it and open PixEz in foreground, leaving Pixivision open in background.
related: https://stackoverflow.com/questions/9312499/android-detect-webview-url-change

**Comment by ultranity** [comment]
Thanks for your feedback!
This part actually works as you expected, But it seems that pixiv changed the URL response args, thus the previous interception detection method failed and caused this bug, which will be fixed in the next release

**Comment by takase1121** [comment]
I see. I'm looking forward for it!
