### ISSUE TITLE
收藏图片分类功能

### ISSUE THREAD

**Issue by hanfeng8** [ultranity/Pix-EzViewer#31]
作者大大，有没有可能给个人收藏搞个像网页端那样，可以自己自定义添加标签对收藏的图片进行分类，这个功能对翻自己收藏的图来说挺方便的，实现起来会不会很困难

**Comment by ultranity** [comment]
图像页，收藏的时候长按♥有惊喜（收藏前）

**Comment by ultranity** [comment]
类似的，画师其实也可以长按私密关注

**Comment by hanfeng8** [comment]
> 类似的，画师其实也可以长按私密关注

哦哦，感谢
