### ISSUE TITLE
zh-rtw  語系不正確，會出現簡體

### ISSUE THREAD

**Issue by skysumbra** [ultranity/Pix-EzViewer#32]
**问题描述**
zh-rtw  語系不正確，會出現簡體，這應該是要繁體中文吧

**如何复现**
將語系使用zh-rtw ，觀察所有文字

**正常&异常表现**
需要全部顯示繁體

**BugReport**

**环境说明**
nokia 5.1 Plus Android 10

**附加**
無

**Comment by ultranity** [comment]
有些翻译不太完善，包括日文也有这种情况，之后有机会统一更新一波

**Comment by ultranity** [comment]
后续发现有翻译不到位欢迎反馈

**Comment by skysumbra** [comment]
用1.7.4R ver107 來feedback
設定頁面內
1.沒有網路的時候，執行檢查更新
2.自定義保存格式內
3.支援頁面
