### ISSUE TITLE
图片加载速度较慢，是优化问题还是什么

### ISSUE THREAD

**Issue by hanfeng8** [ultranity/Pix-EzViewer#33]
**您的功能请求是否与某个问题相关？**
请清晰简洁的描述一下问题所在

**描述你想要的解决方案**
清晰而简洁的描述你认为应当发生的事情

**描述您考虑过的替代方案**
对您考虑过的任何备选解决方案或功能的清晰而简明的描述。

**附加**
在此处添加其他有关的任何内容。

**Comment by ultranity** [comment]
首次启动的加载速度下次更新还会优化一点，其他主要还是受网络运营商影响
