### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Anlonekrly** [ultranity/Pix-EzViewer#34]
请问下现在是维护吗？显示socket is closed？

**Comment by ultranity** [comment]
何种情形？什么环境？

**Comment by Anlonekrly** [comment]
登录显示如下图
![Screenshot_20200924_102155_com perol asdpl play pixivez](https://user-images.githubusercontent.com/71775826/94093425-c3426000-fe4f-11ea-9641-46950dbd9c90.jpg)
![Screenshot_20200924_102152_com perol asdpl play pixivez](https://user-images.githubusercontent.com/71775826/94093442-cb020480-fe4f-11ea-9db9-2311293130bc.jpg)

**Comment by Anlonekrly** [comment]
就是socket is closed 只有今天凌晨的时候登了一会，现在又进不去了

**Comment by ultranity** [comment]
一会儿会推送更新修复
