### ISSUE TITLE
登录不上，是在维护吗？

### ISSUE THREAD

**Issue by Anlonekrly** [ultranity/Pix-EzViewer#36]
大概就是昨天晚7点左右登录不上去，在github重新下载后，登录界面显示如下图
![Screenshot_20200924_102155_com perol asdpl play pixivez](https://user-images.githubusercontent.com/71775826/94094765-e8849d80-fe52-11ea-815c-cb7efcdfc898.jpg)
![Screenshot_20200924_102152_com perol asdpl play pixivez](https://user-images.githubusercontent.com/71775826/94094772-ed495180-fe52-11ea-9285-6227d2dc9288.jpg)

**Comment by HeNrY7107** [comment]
我的也是这个问题，求解

**Comment by HeNrY7107** [comment]
> 我的也是这个问题，求解

试点击右上3点开启设置然后把直连关掉试试看，我的关了就ok了

**Comment by zzw5561122** [comment]
有一个邪路登录方法，更楼上说的一样，把直连关掉，然后科学上网进行登录，进去之后把直连打开，重启应用就OK了

**Comment by ultranity** [comment]
一会儿会推送更新修复
