### ISSUE TITLE
解释下为什么每次登录不停跳出验证身份 登不上去

### ISSUE THREAD

**Issue by SKTBaker** [ultranity/Pix-EzViewer#37]
能有个答复吗 最近上不去很苦恼

**Comment by SKTBaker** [comment]
ZZZZZ

**Comment by zzw5561122** [comment]
> ZZZZZ

试点击右上3点开启设置然后把直连关掉，然后科学上网进行登录，进去之后把直连打开，重启应用就OK了

**Comment by SKTBaker** [comment]
> > ZZZZZ
> 
> 试点击右上3点开启设置然后把直连关掉，然后科学上网进行登录，进去之后把直连打开，重启应用就OK了

有效果 但第二天还是要科技 这是什么问题呢

**Comment by zzw5561122** [comment]
> > > ZZZZZ
> > 
> > 
> > 试点击右上3点开启设置然后把直连关掉，然后科学上网进行登录，进去之后把直连打开，重启应用就OK了
> 
> 有效果 但第二天还是要科技 这是什么问题呢

这个就得问做了大佬了

**Comment by ultranity** [comment]
一会儿会推送更新修复
