### ISSUE TITLE
1.7.0R闪退

### ISSUE THREAD

**Issue by JetLiu233** [ultranity/Pix-EzViewer#38]
**问题描述**
启动应用进入介面后即报错，然后闪退

**如何复现**
启动应用

**正常&异常表现**
更新1.7.0R后出现，以往版本无此问题

**BugReport**

![S00926-01215580](https://user-images.githubusercontent.com/63274744/94297717-897c7100-ff97-11ea-90eb-84173041939b.png)

**环境说明**
 - 设备:魅族16th
 - 系统:Android 8.1.0
 - 软件版本 1.7.0R

**附加**
在此处添加其他有关的任何内容。

**Comment by JetLiu233** [comment]
关闭「不启用直连」后问题消失

**Comment by ultranity** [comment]
感谢反馈，后续修复
