### ISSUE TITLE
貌似最近又连接出问题了

### ISSUE THREAD

**Issue by SKTBaker** [ultranity/Pix-EzViewer#40]

**Comment by SKTBaker** [comment]
> _没有提供描述。_

不停刷新身份

**Comment by ZhMJiang** [comment]
这边也是，上海教育网和移动4G都不行，加载不出首页图片，在弹出"刷新身份认证"提示后无限转圈
![Uploading Screenshot_20201007_234755_com.perol.asdpl.play.pixivez.jpg…]()

**Comment by ultranity** [comment]
应用内更新随机推送了一部分1.7.2R版本的，就是想定位一下哪里的原因，比较闹心的是复现没什么规律，有兴趣可以对比下两个版本的情况

如果刷新了身份信息这种情况，切一下tab页面或者强制关闭app后重新进入试试，换个请求基本就可以解决

**Comment by ZhMJiang** [comment]
获取身份信息后切换tag和强制退出仍不能访问，昨晚至今都是这样-------- 原始邮件 --------发件人： elucida <notifications@github.com>日期： 2020年10月8日周四 10:43收件人： ultranity/Pix-EzViewer <Pix-EzViewer@noreply.github.com>抄送： ZhMJiang <foshanjzm@126.com>, Comment <comment@noreply.github.com>主    题： Re: [ultranity/Pix-EzViewer] 貌似最近又连接出问题了 (#40)
应用内更新随机推送了一部分1.7.2R版本的，就是想定位一下哪里的原因，比较闹心的是复现没什么规律，有兴趣可以对比下两个版本的情况
如果刷新了身份信息这种情况，切一下tab页面或者强制关闭app后重新进入试试，换个请求基本就可以解决

**Comment by 1078249029** [comment]
狂刷身份验证，无论自己开不开梯子都登不上去

**Comment by ultranity** [comment]
app内更新一下 1.7.3R，还有问题的话回复一下系统版本+网络状态

**Comment by 1078249029** [comment]
安卓10 color os7.1 pez ver1.7.2r
![Screenshot_2020-10-08-22-29-40-84_4b917d10dd463a191f2cd7bd0a2e90b5](https://user-images.githubusercontent.com/62127946/95473163-677ee780-09b6-11eb-8456-8539aca67a3b.jpg)
#
![Uploading Screenshot_2020-10-08-22-29-52-74_4b917d10dd463a191f2cd7bd0a2e90b5.jpg…]()

**Comment by 1078249029** [comment]
联通流量 无论开不开梯子走不走内置代理都打不开
先谢谢大佬了

**Comment by SKTBaker** [comment]
APP内直接更新吗

**Comment by sidleier** [comment]
MI 9，Android 10，MIUI 12.0.3.0，电信4G，移动4G。关直连挂梯可以看。

**Comment by SKTBaker** [comment]
最新版就是1.71R 没有1.72 73啊

**Comment by ultranity** [comment]
更新一下1.7.4R，后续情况欢迎反馈

**Comment by 1078249029** [comment]
谢谢大大，bug已经修复了
