### ISSUE TITLE
Any chance for an English UI?

### ISSUE THREAD

**Issue by fluffyloopy** [ultranity/Pix-EzViewer#41]

**Comment by ultranity** [comment]
You can change the language in app settings, although some translations are not perfect.

**Comment by IzzySoft** [comment]
Well, if you can find settings that is, with the entire app in Chinese, and figure you have to restart the app (and how to do that) :wink: Maybe you should query the system language at first start, @ultranity – and if it's not ZH (or any of the other supported by your app), use English. Imperfect as it might be, it's WAAAYYY better for non-Chinese-speakers. By the way: inclusion with F-Droid waits for that, as we do not want to "scare" your users :smile:

@fluffyloopy please see [my post here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8040#note_477886946) for how you can switch. In short: tap the menu button in the upper-right (its label means "settings"). Scroll down the screen, a few phrases are in English – one of them is "Language". Tap that, tap "en". On the popup that appears, tap the "blue text" in the lower right. Wait a few secs, app should switch to English. That "blue text" means "restart now", as I found out later – I restarted by force-closing the app as I could not figure either :see_no_evil:

**Comment by ultranity** [comment]
sorry for not notice this bug, I will try to fix this by this weekend

**Comment by IzzySoft** [comment]
Thanks! Please give me a ping when it's fixed, so I can proceed integrating your app with F-Droid. And no worries, bugs happen. Good when they are fixed quickly :smiley: :crossed_fingers:

**Comment by linsui** [comment]
Hi, according to https://github.com/ultranity/Pix-EzViewer/issues/35 this app will be deprecated and it's declared as that in https://github.com/Notsfsssf/Pix-EzViewer . Could you clarify tou decision? Thanks!

**Comment by ultranity** [comment]
Considering that almost every feature I could conceive has been implemented, there won't need and won't be many updates in the future. To some extent, the functionality of this project has been finalized.

So as mentioned, it's recommended (by [Notsfsssf](https://github.com/Notsfsssf)) to switch to [the flutter verion](https://github.com/Notsfsssf/pixez-flutter) for better UI(especially animation), better user experience and coding experience. When programming, it's easier to rebuild from scratch than to understand and edit old applications :), not mentioning that there is a new wheel -- Flutter.

But I still "like" this "old version", so there will be a basic maintenance. I will try to maintain it if (and maybe only if) it need some bug fix.

**Comment by IzzySoft** [comment]
Thanks @ultranity! I've now processed the MR at F-Droid. I've added the `NonFreeNet` AntiFeature as the service is commercial (and not FOSS). Please point out in the app's description that the app requires an existing account.

**Comment by ultranity** [comment]
@IzzySoft fastlane description updated

**Comment by IzzySoft** [comment]
@ultranity thanks! Is that update tagged? If you're fast, you can reuse the current last tag (as long as the build has not yet been processed by our buildserver – never do that with releases already built). Else it will be fetched with the next update.
