### ISSUE TITLE
家里换了无线网 现在图片出一张要半天 

### ISSUE THREAD

**Issue by SKTBaker** [ultranity/Pix-EzViewer#43]
，

**Comment by SKTBaker** [comment]
希望得到解决

**Comment by ultranity** [comment]
这个问题和区域有关，取决于你的网络与pixiv服务器的连接情况，但在我能测试的范围内联通电信移动三网的表现差异不大没有出现哪个变得不可用，但还有一种可能是换网触发了pixiv的某种ip警报机制，若是如此过几天情况会有好转
