### ISSUE TITLE
首页滑动手势

### ISSUE THREAD

**Issue by efsg** [ultranity/Pix-EzViewer#44]
现在的手机尺寸太大了，够不到顶栏，用底栏或者Darwin手势左右滑动Tab比较好

**Comment by ultranity** [comment]
1.8.0R 后调整了使用手势切换tab的逻辑，体验尚可。底栏要做的改动比较多暂时不考虑，可以体验一下[Shaft](https://github.com/CeuiLiSA/Pixiv-Shaft)或者[pixiv-flutter](https://github.com/Notsfsssf/pixez-flutter)
