### ISSUE TITLE
加载不出缩略图，基本玄学找图，版本0.32

### ISSUE THREAD

**Issue by Anlonekrly** [ultranity/Pix-EzViewer#45]
![Screenshot_20210119_012324_com perol pixez](https://user-images.githubusercontent.com/71775826/104946392-eee7e800-59f4-11eb-944f-ee4fc6a5c5a3.jpg)
![Screenshot_20210119_012403_com perol pixez](https://user-images.githubusercontent.com/71775826/104946385-ebecf780-59f4-11eb-8011-98feef33d04e.jpg)
一分钟加载不了缩略图，而且下载也基本卡在seed就不会动了

不知道为什么
正常应该就是缩略图然后打开下载
希望解决

**Comment by Max-Learning** [comment]
同样问题
18日下午开始无法加载与下载图片，包括用户头像、插画略缩图与大图，显示图片加载失败；插画简介、小说文字等其他信息可正常加载。18日中午使用正常。
同类软件出现相同问题
pixez为最新版

**Comment by ultranity** [comment]
已修复
