### ISSUE TITLE
设置正确的情况下无法登录

### ISSUE THREAD

**Issue by JetLiu233** [ultranity/Pix-EzViewer#47]
●BUG描述
无法登录账号，账号密码已再三确认正确，当关闭「不启用直连」选项时报错为
「其他错误，检查接入点APN是否为Net而不是WAP，检查网络是否通畅
HTTP 400 Bad Request
Invalid grant_type parameter or parameter missing」
「不启用直连」选项启用时，并启用SSR代理，报错为
「Socket is closed」

●网络条件
apn接入点已设为net，使用中国移动的运营商网络

●信息
机型：魅族16th 64G 全网通
安卓版本：8.1.0
APP版本：1.7.7R

**Comment by emerhythm** [comment]
我跟你一样

**Comment by henryEX** [comment]
由于p站鉴权接口改动，需要等待开发者修复。已登录的用户可正常使用，仅影响未登录的用户

**Comment by moosescap** [comment]
同樣的情況，魅族16t，移動聯通都不行，裂開了我為啥要給手機清數據

**Comment by phigros1346** [comment]
一样不行，以前可以现在重新下下来登录不了了

**Comment by LZTSGS** [comment]
希望能够快点修复………………

**Comment by ultranity** [comment]
请更新，已修复
