### ISSUE TITLE
大图页面存图导致“单独R80文件夹”失效

### ISSUE THREAD

**Issue by sidleier** [ultranity/Pix-EzViewer#49]
**问题描述**
开启“创建单独R80文件夹”后，如果在图片详情页里点进大图后长按保存，图片会被存入表文件夹，且文件名开头自己带一个“?”。其他点其他地方的下载不会出现上述问题。

**如何复现**
1. 开启“创建单独R80文件夹”
2. 找到一张R80图，进入图片详情页，点进大图，等加载完，长按保存
3. 查看手机相册的表里两个文件夹
4. 发现上述问题

**正常&异常表现**
上述。

**BugReport**
![IMG_20210430_122659](https://user-images.githubusercontent.com/72584975/116648853-b0db5800-a943-11eb-96f5-50868db34b38.jpg)
![IMG_20210430_123540](https://user-images.githubusercontent.com/72584975/116648856-b2a51b80-a943-11eb-82b3-4a087e1d0d16.jpg)

**环境说明**
 - 设备: [e.g. XiaoMi 9]
 - 系统: [e.g. Android 10]
 - 软件版本 [e.g. 1.7.7R]

**附加**
在此处添加其他有关的任何内容。

**Comment by ultranity** [comment]
下个版本修复
