### ISSUE TITLE
[建议]一些体验上的问题

### ISSUE THREAD

**Issue by naloder** [ultranity/Pix-EzViewer#52]
目前那个对于捐赠的提示过于抢眼，导致很多情况下，在存图或者其他情况下一直弹出，有没有可能用侵入性更小一点的方式来提醒。另外可以的话可不可以试着支持评论区表情显示和屏蔽评论区广告

**Comment by ultranity** [comment]
- 捐赠的提示下个版本会移除
- 评论区表情显示需要研究一下
- 评论区广告我没怎么见过... 有什么实例或者可行的屏蔽规则吗？

**Comment by naloder** [comment]
@ultranity 评论区广告过滤在隔壁的[Pixiv-Shaft](https://github.com/CeuiLiSA/Pixiv-Shaft)中有相关实现。。大概可以参考下。。

**Comment by naloder** [comment]
https://github.com/ultranity/Pix-EzViewer/commit/ce464da0df67d6ef1102a5d8449709454637cffa
这个fix被舍弃了吗?

**Comment by ultranity** [comment]
> [ce464da](https://github.com/ultranity/Pix-EzViewer/commit/ce464da0df67d6ef1102a5d8449709454637cffa) 这个fix被舍弃了吗?

?舍弃是说？

**Comment by naloder** [comment]
新版本中捐赠弹窗仍然在不适当的时机弹出 
上版本中该commit已经解决的问题
新版本再次出现了 是不是revert了这部分还是其他问题(?

**Comment by naloder** [comment]
@ultranity 新版本中捐赠弹窗仍然在不适当的时机弹出
上版本中该commit已经解决的问题
新版本再次出现了 是不是revert了这部分还是其他问题(?

**Comment by ultranity** [comment]
> @ultranity 新版本中捐赠弹窗仍然在不适当的时机弹出 上版本中该commit已经解决的问题 新版本再次出现了 是不是revert了这部分还是其他问题(?

这个新版本是什么渠道下载的？确定是1.8.3 release？按说不应该出现这种情况，我这边也没法复现

**Comment by naloder** [comment]
@ultranity 确实是183 以及这是截图![图](https://www.helloimg.com/images/2022/10/12/Zg9wkq.jpg)

**Comment by ultranity** [comment]
@naloder  。。。兄台你的截图好像没上传全，再发一下？

甚至发下你目前安装的apk？

**Comment by naloder** [comment]
截图地址已经修改,apk用的是 https://github.com/ultranity/Pix-EzViewer/releases/tag/1.8.3 里面的

**Comment by ultranity** [comment]
- [x] 评论区表情显示

再试下弹窗，还不行的话清除app数据后重新登陆试试？虽然有些选项要重新设置

**Comment by naloder** [comment]
弹窗目前仅在关于界面展示一次之后就没在强制出现了(? 
似乎是行为正常了(总感觉弹窗提示这种本身侵入性太大了还不能叉掉(x

**Comment by ultranity** [comment]
其实是当时做的太简陋但按说那个对话框随便点击外部或者返回都会自动取消
评论区广告有需要单独开一个issue吧
