### ISSUE TITLE
登录不了，显示连接错误

### ISSUE THREAD

**Issue by yuanmengyisheng** [ultranity/Pix-EzViewer#53]
**问题描述**
请清晰简洁的描述一下问题所在

**如何复现**

**正常&异常表现**
清晰的描述你认为应当发生的事情

**BugReport**
可能的话附上截屏、logs 等信息

**环境说明**
 - 设备: [e.g. XiaoMi 10]
 - 系统: [e.g. Android 10]
 - 软件版本 [e.g. 1.5.6R]

**附加**
在此处添加其他有关的任何内容。

**Comment by austinhuang0131** [comment]
#47?

**Comment by yuanmengyisheng** [comment]
connect failed : ECONNREFUSED ( Connection refused )

**Comment by ultranity** [comment]
问题描述
请清晰简洁的描述一下问题所在

如何复现

BugReport
可能的话附上截屏、logs 等信息

环境说明

设备: [e.g. XiaoMi 10]
系统: [e.g. Android 10]
软件版本 [e.g. 1.5.6R]

附加
在此处添加其他有关的任何内容。

**Comment by yuanmengyisheng** [comment]
就开着代理输入账号点登陆之后，一直在登录界面不动了，邮箱也能收到账号的登录信息，就是进不去。mate40pro 鸿蒙系统不行，魅族pro6plus的安卓7也不行

**Comment by ultranity** [comment]
先用这个 [app-bugly_dev_release1.8.2.zip](https://github.com/ultranity/Pix-EzViewer/files/7777092/app-bugly_dev_release1.8.2.zip)
will be fixed in next release but I need some time to clean up those codes before formally releasing it.

**Comment by ultranity** [comment]
fixed in latest release
