### ISSUE TITLE
App bar actions seems to be missing from PictureActivity

### ISSUE THREAD

**Issue by ohaiibuzzle** [ultranity/Pix-EzViewer#54]
**Describe the bug**
After updating to 1.8.0R, the buttons for Back and Share actions seems to be missing from PictureActivity

**To Reproduce**
1. Open any artwork
2. Observe the top bar, which seems to be completely gone

**Expected behavior**
Top bar with a back button to return to the previous screen and a share button that triggers the Share sheet

**Screenshots**
![screen](https://user-images.githubusercontent.com/23693150/142586846-f964c9ba-2cbe-4a85-9dd3-ea3f3c1ad517.png)

**Smartphone (please complete the following information):**
 - Device: LG V50 ThinQ
 - OS: Android 11.0
 - Version: 1.8.0R ver 111

I tried to dig into the code but I can't seem to figure out what it was. It seems to happen with the latest commit as well

**Comment by ultranity** [comment]
check this ver. [app-bugly_dev_release1.8.2.zip](https://github.com/ultranity/Pix-EzViewer/files/7777092/app-bugly_dev_release1.8.2.zip)
will be fixed in next release but I need some time to clean up those codes before formally releasing it.

**Comment by ohaiibuzzle** [comment]
Looks like it works as expected now 😀
