### ISSUE TITLE
I can't login. My email and password are correct. 

### ISSUE THREAD

**Issue by sombresu** [ultranity/Pix-EzViewer#58]
**Describe the bug**
Can't login this app. I try to login in browser and it's fine

**To Reproduce**
Press login, input email or ID and password. Not working. Failed to connect error message. 

**Expected behavior**
Successfully login, because my email, id and password are correct 

**Smartphone (please complete the following information):**
 - Device: [Poco x3 nfc]
 - OS: [miui 12.5]
 - Browser [kiwi browser] 
 - Version [latest]

**Additional context**

**Comment by Fijxu** [comment]
I got the same error, i tried login with 2 diferent browsers, and the error is the same

![ss.png](https://user-images.githubusercontent.com/61166695/147396633-be82c6a0-1816-4d6d-aae1-bab0a9f6ca26.png)

**Comment by ultranity** [comment]
[app-bugly_dev_release1.8.2.zip](https://github.com/ultranity/Pix-EzViewer/files/7777092/app-bugly_dev_release1.8.2.zip)
will be fixed in next release but I need some time to clean up those codes before formally releasing it.
