### ISSUE TITLE
无法解析程序包

### ISSUE THREAD

**Issue by MyBlueHorizon** [ultranity/Pix-EzViewer#6]
**问题描述**
如题
**如何复现**
打开apk安装
**环境说明**
**Smartphone (please complete the following information):**
 - OS: Android 4.4 32bit
 - Version1.5.6B

是否不兼容旧版32位设备？

**Comment by ultranity** [comment]
Android 4.4以前的release是不支持的，后面我会考虑重新加回,但缺少测试，我可以先给你发一个试试能不能用
[app-debug.zip](https://github.com/ultranity/Pix-EzViewer/files/4840440/app-debug.zip)
后缀手动改回apk

**Comment by MyBlueHorizon** [comment]
测试了一下，打开就停止运行

**Comment by ultranity** [comment]
具体是什么架构？armeabi，armeabi-v7a，x86？

**Comment by MyBlueHorizon** [comment]
armeabi-v7a

**Comment by ultranity** [comment]
要补全对4.4向下兼容工程量太大了，同时要放弃好几个库，不考虑动工，你有心的话可以删减一版自用

**Comment by ultranity** [comment]
后续会在readme里说明兼容问题，感谢反馈
