### ISSUE TITLE
Login page refreshes to the main page after device rotation

### ISSUE THREAD

**Issue by mmc20520** [ultranity/Pix-EzViewer#60]
**Describe the bug**
Login page refreshes to the main page after device rotation

**To Reproduce**
1. Go to login page
2. Randomly browse in the webview
3. Rotate screen
4. You will see the main page again

**Expected behavior**
The web content should remain unchanged

**Screenshots**
Before rotation:

![pic13](https://user-images.githubusercontent.com/100833575/156729388-9dc2b050-54fc-4d56-9fb5-d76b6065e0cd.png)

After rotation:
![pic14](https://user-images.githubusercontent.com/100833575/156729412-22c1a9ac-02af-493f-8f5c-0fdf0d00b308.png)

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: Android 10
 - Browser: webview
 - Version: 1.8.0R ver 111

**Comment by vivysfans** [comment]
Maybe you can try clicking the address appearing from the Issue ＃53.

**Comment by ultranity** [comment]
fixed in latest release

**Comment by ultranity** [comment]
fixed
