### ISSUE TITLE
F-Droid can't build - aapt error

### ISSUE THREAD

**Issue by licaon-kter** [ultranity/Pix-EzViewer#62]
df88e9637c0858f43aeb917c9624334a8faf8db5

```
Execution failed for task ':app:processLibreReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/builds/fdroid/fdroiddata/build/com.perol.asdpl.play.pixivez.libre/app/src/main/res/menu/activity_hello_m_drawer.xml:41: AAPT: error: resource drawable/ic_action_block (aka com.perol.asdpl.play.pixivez.libre:drawable/ic_action_block) not found.
```
Log: https://gitlab.com/fdroid/fdroiddata/-/jobs/3256205521#L522

Ref: https://gitlab.com/fdroid/fdroiddata/-/commit/bc88bd31ad3b487b3ad674fd1835a943a4f32cf4

**Comment by ultranity** [comment]
some icon is now placing in wrong folder due to android flavour settings, I will fix this soon but could F-droid rebuild this or update until next release? @licaon-kter

**Comment by licaon-kter** [comment]
You did not retag so I've updated manually: https://gitlab.com/fdroid/fdroiddata/-/commit/ce31f4a4966618210c3a41a524c5aeb81d407f63

**Comment by ultranity** [comment]
thanks for your help 👍
