### ISSUE TITLE
「AI生成作品」

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#63]
「AI生成作品」图片的标签能否加入，并靠前优先显示
![Screenshot_20221108110643](https://user-images.githubusercontent.com/67962258/200466051-f65ec21a-7b40-4c5c-a5ca-e0e283a2f69c.png)

**Comment by LZTSGS** [comment]
> 「AI生成作品」图片的标签可以加入，并靠前显示优先 ![截图_20221108110643](https://user-images.githubusercontent.com/67962258/200466051-f65ec21a-7b40-4c5c-a5ca-e0e283a2f69c.png)

**Comment by LZTSGS** [comment]
对了，下载多P图片命名时遇到大于10张的作品，能否使数字序号加0补齐位数。有很多软件都没有按实际数字大小排序的功能，导致不太方便浏览。能否考虑一下。

**Comment by ultranity** [comment]
AI生成作品这个TAG还需要调查一下，没太注意这点，Pixiv官方似乎并没有给标注对应的TAG

序号加0补齐位数这个需求可以理解，后面考虑加入

**Comment by LZTSGS** [comment]
> AI生成这个作品TAG还需要调查一下，没太注意这个点，官方似乎并没有给Pixiv标注的TAG
> 
> 可以将编号加0补齐暴露这个需求，提前考虑



> AI生成作品这个TAG还需要调查一下，没太注意这点，Pixiv官方似乎并没有给标注对应的TAG
> 
> 序号加0补齐位数这个需求可以理解，后面考虑加入

官方的“AI生成”只有作者主动添加才有用，我觉得按官方的标准，适配下这个“AI生成”就行了，保存时最好能写进tag。
![IMG_20221112_080047](https://user-images.githubusercontent.com/67962258/201447848-52f69a5c-de7e-4b70-bf6e-69a65d340754.jpg)
![Screenshot_2022-11-12-08-02-13-85](https://user-images.githubusercontent.com/67962258/201448172-6da55a21-d277-4ba6-ad19-094f05bcc934.jpg)

说到ai作品，官方那好像有专属的ai作品排行榜了，能否考虑适配一下，感觉排行里还是有些不错的作品
![Screenshot_20221112080708](https://user-images.githubusercontent.com/67962258/201448072-cc3b20b2-cda4-4b25-815a-4d27ca52087c.png)

**Comment by ultranity** [comment]
@LZTSGS 
调查了一下，AI生成作品这个TAG本身没有被特殊对待就是普通TAG，如果存在保存时就会被写入

靠前显示或许会通过提供tag排序功能变相实现

列表API很简单就猜出来了，免了抓包，个人体验还行，下版加入

序号加0补齐位数下版加入，会需要改保存模板

**Comment by sidleier** [comment]
可否考虑加入用户屏蔽功能，毕竟有些用户根本不加ai绘tag。

**Comment by ultranity** [comment]
2.0.0 发布, 加入了船新的列表过滤系统，可以体验下 @sidleier @LZTSGS
