### ISSUE TITLE
Add option to sort by NSFW/SFW

### ISSUE THREAD

**Issue by nonetrix** [ultranity/Pix-EzViewer#65]
I cannot read Chinese so I will just say this in English and translate using ChatGPT, I'm sorry if there are mistranslations.

Currently there seems to be no way of shorting the category of images e.g. "a" and "b", could this be added? I only want to see "a" images, or "b" images in recommend

我不会读中文，所以我只能用英文说，并使用ChatGPT进行翻译，如果翻译有误，请多多谅解。目前似乎没有办法将图像分类缩短，例如NSFW和SFW，能否增加这个功能呢？我只想看到推荐中的NSFW图像或SFW图像。
![Screenshot_20230124-012449~2](https://user-images.githubusercontent.com/45698918/214234144-8e134440-b4ff-4448-bcd5-a270fccd0f6e.png)

**Comment by ultranity** [comment]
try this feature in 2.0.0 via list filter

**Comment by nonetrix** [comment]
Oh sorry about me saying "a" or "b" images, that was to bypass ChatGPT censorship and I didn't notice it lmao
