### ISSUE TITLE
能只下載像網頁版預覽大小的圖片嗎？

### ISSUE THREAD

**Issue by GHolk** [ultranity/Pix-EzViewer#66]
實際上我不需要 medium 或 large 大小的影像，他們都太大了，而且有時候是 png 格式。
能否直接下載網頁版顯示的 jpeg 格式影像？
網址格式是 `https://i.pximg.net/img-master/img/2018/02/14/01/02/59/67261030_p0_master1200.jpg` 。
但查閱 pixiv api 似乎不會返回這種網址？
請問有可能使用這種網址來下載圖片嗎？

**Comment by GHolk** [comment]
如果想使用此功能可以到我的 repo 的 release 下載 apk

https://github.com/GHolk/Pix-EzViewer/releases/tag/1.9.0-gholk-variant

**Comment by ultranity** [comment]
已添加进主线
