### ISSUE TITLE
Visible "follow artist" button?

### ISSUE THREAD

**Issue by MikaelaML2xR** [ultranity/Pix-EzViewer#68]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Just got the app and I can't follow artists because the button doesn't seem to exist!!!!

**Describe the solution you'd like**
FOLLOW ARTIST BUTTON

**Describe alternatives you've considered**
A BUTTO beside a user's profile or in the art  #section

**Additional context**
I authored this request at 2 am. Hellp
![Screenshot_20230522-020139_Pix-EzViewer](https://github.com/ultranity/Pix-EzViewer/assets/93539285/326b5051-3701-49bf-9c48-0346db2f1b0a)

![Screenshot_20230522-020131_Pix-EzViewer](https://github.com/ultranity/Pix-EzViewer/assets/93539285/0a984cf5-11e3-481a-8f34-7229b3134f86)

**Comment by GHolk** [comment]
click the `+` button at the right-bottom corner to follow the artist.

**Comment by MikaelaML2xR** [comment]
> click the `+` button at the right-bottom corner to follow the artist.

Could you send a screenshot? I don't see it anywhere

**Comment by GHolk** [comment]
this round button in your screen shot.

![圖片](https://github.com/ultranity/Pix-EzViewer/assets/13307281/8211e268-c5b1-4fb8-9bce-8e9504ff0f56)

**Comment by ultranity** [comment]
Now there is a more intuitive follow button in users view, try it @MikaelaML2xR @GHolk
