### ISSUE TITLE
F-Droid packaging

### ISSUE THREAD

**Issue by namazso** [ultranity/Pix-EzViewer#7]
Would it be possible to have this app available on F-Droid?

**Comment by ultranity** [comment]
Maybe oneday but not now, F-Droid requires to remove all trace/debug libs but currently we still need it.
Besides, the priority of distributing in app stores is not high, But I will add this to TODO list.
Feel free to share the app with your friends (and use the in-app updating).

**Comment by namazso** [comment]
> F-Droid requires to remove all trace/debug libs but currently we still need it.

it does not. only proprietary libraries are disallowed:

> We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase. Please talk to upstream about an untainted build flavor (either using a FLOSS analytics software like ACRA or by removing Non-Free dependencies completely).

also, in this case I'll try to make a libre fork for packaging
