### ISSUE TITLE
Some image blocked from appview

### ISSUE THREAD

**Issue by Kilikx2** [ultranity/Pix-EzViewer#70]
Some Image are block from being viewed on app but it works on browser webview

**To Reproduce**
1. Access specific works via e.g: https://www(.)pixiv(.)net/en/artworks/106043575

**Expected behavior**
The work can be accessed normally

**Screenshots**
This prompt appear on the work listing if it is in our bookmark. Only on app.
![Screenshot_20230726-203443-139](https://github.com/ultranity/Pix-EzViewer/assets/109612777/dc4b6b86-7c5c-4fe6-a804-6ec95fe57b18)

**Smartphone (please complete the following information):**
 - Device: Moto G82
 - OS: Android 11

**Comment by ultranity** [comment]
those contents are blocked by pixiv official api due to Pixiv & Google Play policy, there is nothing to do unless Pixiv change the permision.
