### ISSUE TITLE
1.8.8和1.8.5都：搜索画师拉到最底下会「一直自动翻页」，1.8.3正常

### ISSUE THREAD

**Issue by RoberHung** [ultranity/Pix-EzViewer#74]
1.8.8和1.8.5 按名称搜画师拉到最底下后都会「自动翻页」，很快地自动连续显示「第二页」、「第三页」……，此时手指上滑屏幕则会停在当前页且无法看「上一页」。1.8.3则正常

Android 10
红米 K30S 稳定版 MIUI12.0.10

**Comment by ultranity** [comment]
自动加载下一页是预期功能，但是上滑后无法看上一页这个情况我这边无法复现，可以更新2.0.0试下有无改善，或者提供相应情况的截图
