### ISSUE TITLE
2.0.0版本登录闪退

### ISSUE THREAD

**Issue by TCOTC** [ultranity/Pix-EzViewer#75]
**问题描述**
尝试了应用内：Google登录、账号密码登录、「选择浏览器登录」：Google登录、账号密码登录，在点击登录后出现短暂的白屏，随后闪退

![c4ecef56b691dd432529d28defaec7a](https://github.com/ultranity/Pix-EzViewer/assets/78434827/15739dd0-df27-4173-a746-0966b55dbd0e)

**环境说明**
 - 设备: OPPO K9 Pro
 - 系统: Android 13  ColorOS 13.1
 - 软件版本 2.0.0

**Comment by ultranity** [comment]
。发现一处登录bug，今天修复

**Comment by ultranity** [comment]
版本已更新 @TCOTC ，重新下载登录试试

**Comment by TCOTC** [comment]
可以登录了
