### ISSUE TITLE
点击「登录帮助」没有反应且点击「确定」时闪退

### ISSUE THREAD

**Issue by TCOTC** [ultranity/Pix-EzViewer#76]
**问题描述**

点击「登录帮助」没有反应且点击「确定」时闪退

![7f71545107f8d1c20939c948c8237de](https://github.com/ultranity/Pix-EzViewer/assets/78434827/0e53af1c-86c9-4914-80c3-51b75a960814)

**环境说明**

- 设备: OPPO K9 Pro
- 系统: Android 13 ColorOS 13.1
- 软件版本 2.0.0

**Comment by ultranity** [comment]
Token登录功能是帮助账户迁移和调试用的（忘了写帮助内容xs），请按登录按钮（如果网络有问题挂梯）登录
