### ISSUE TITLE
无法下载图片

### ISSUE THREAD

**Issue by TCOTC** [ultranity/Pix-EzViewer#77]
只要点下载就会这样：

![b1957106045bab76ae14c8b43dc8178](https://github.com/ultranity/Pix-EzViewer/assets/78434827/8010507e-5e7d-41e0-8849-2261bcbf34be)

**Comment by ultranity** [comment]
这个没能复现
在设置内最下有查看报告功能，发下日志记录

另外确认下有没有存储权限

**Comment by TCOTC** [comment]
「查看报告」好像少了个复制按钮，长按不能复制

**Comment by ultranity** [comment]
更新版本试试看还能复现么？

**Comment by ultranity** [comment]
看上去是添加屏蔽用户功能的数据库迁移写的不够稳健

@TCOTC
[PixEzViewer-2.1.0-git-universal-release.zip](https://github.com/user-attachments/files/18032220/PixEzViewer-2.1.0-git-universal-release.zip)
 试下这个版本

**Comment by TCOTC** [comment]
![Screenshot_2024-12-06-12-51-55-44_4b917d10dd463a191f2cd7bd0a2e90b5.jpg](https://github.com/user-attachments/assets/a262c7b9-6f27-4ad2-b481-6fd1ecb18636)

**Comment by ultranity** [comment]
emmm更新下2.1.1，如果还不行的话清理下应用数据吧bro，但会需要重新登录

**Comment by TCOTC** [comment]
现在能打开 APP 了。

因为换手机了所以不知道在旧手机能不能正常下载，但新手机是能下载的。先关闭了。
