### ISSUE TITLE
inconsistent theming on system components 

### ISSUE THREAD

**Issue by CelestialCrafter** [ultranity/Pix-EzViewer#80]
**Describe the bug**
on the top status bar and navigation buttons, the colors used by pixel are inconsistent with the current theme colors

**To Reproduce**
1. change theme color from the default blue to a different color

**Expected behavior**
The color on the status bar and navigation bar should match the current theme color, and not be default blue no matter the theme

**Screenshots**
![Screenshot_20240329_140926_Pix-EzViewer.png](https://github.com/ultranity/Pix-EzViewer/assets/44733683/00f42ca8-aac6-46e9-a236-5b258c3289e9)

**Smartphone:**
 - Device: Samsung Galaxy S23
 - OS: Android 14
 - Model: S911U
 - App Version 2.0.0

**Additional context**
Doesn't happen in version 1.8.8, only in 2.0.0.
Material 3 and Harmonize colors is on, Dynamic Color is off (although this happens with all configurations for colors)

**Comment by ultranity** [comment]
fixed in 2.1.0
