### ISSUE TITLE
页面设置无法持久化保存

### ISSUE THREAD

**Issue by huajideshutiao** [ultranity/Pix-EzViewer#83]
**问题描述**
如题，调整页面的布局设置重启后会恢复。

**如何复现**
1.
![图1](https://github.com/ultranity/Pix-EzViewer/assets/38980554/10348009-d771-4ca0-b848-6b0092cc08f9)
2.
![图2](https://github.com/ultranity/Pix-EzViewer/assets/38980554/460f5ff9-2dac-44c4-9838-eb0e0f7b0ecb)
3.
![图3](https://github.com/ultranity/Pix-EzViewer/assets/38980554/56f79d99-8c55-49b4-a4c0-6098edce4551)
4.重启应用，进入后如图1

**正常&异常表现**
正常情况下应该保持在图3

**环境说明**
 - 设备: [红米 k70 pro]
 - 系统: [Android 14]
 - 软件版本 [2.0.0]

**Comment by ultranity** [comment]
更新试试，当前版本应该是有保持过滤设置的

**Comment by huajideshutiao** [comment]
> 更新试试，当前版本应该是有保持过滤设置的

可惜还是不行嘞
![Screenshot_2024-12-06-02-02-37-112_com perol asdpl play pixivez](https://github.com/user-attachments/assets/03bc69a3-5418-4bc7-bbbf-44d4c675a0c2)
![Screenshot_2024-12-06-02-02-47-770_com perol asdpl play pixivez](https://github.com/user-attachments/assets/41dc42b7-74fb-4b63-a142-3491d7d2c0a1)
不过上面的漫画过滤是正常的

**Comment by ultranity** [comment]
哦漏了布局设置的持久化，下个版本修一下
