### ISSUE TITLE
允许不显示作品的推荐栏

### ISSUE THREAD

**Issue by huajideshutiao** [ultranity/Pix-EzViewer#84]
**描述你想要的解决方案**
允许设置是否在作品底部自动加载相关作品。因为大部分情况下浏览作品都是比较关注单个或者同作者的作品，如果想要找图一般会在首页推荐寻找而不是在作品推荐中。

**描述您考虑过的替代方案**
目前我正在使用的另一个第三方pixiv客户端 [shaft](https://github.com/CeuiLiSA/Pixiv-Shaft) 的解决方案如下图：
![Screenshot_2024-05-30-08-45-08-159_ceui lisa pixiv](https://github.com/ultranity/Pix-EzViewer/assets/38980554/566e3f12-09cd-4289-be34-33b759214d86)
图中底部的“
![IMG_20240530_084757](https://github.com/ultranity/Pix-EzViewer/assets/38980554/05eca30b-0931-42a3-8e6d-c6987a07cce5)
”这个按钮会跳转到相关作品/推荐作品

**Comment by ultranity** [comment]
准了，下个版本会加个设置项

**Comment by ultranity** [comment]
更新看看，修改设置后需要手动点击加载相关图片

**Comment by huajideshutiao** [comment]
> 更新看看，修改设置后需要手动点击加载相关图片

整挺好，但是我点击相关推荐和查看评论都没啥反应，还发现了个新bug，在详情页快速向上或向下滑动，本来摇一摇的动画会变得非常卡
