### ISSUE TITLE
Download queue fails but direct download works.

### ISSUE THREAD

**Issue by Trung0246** [ultranity/Pix-EzViewer#89]
**Describe the bug**
Currently whenever adding images to download queue it will automatically fails. However download directly by viewing the image then long press still works. No matter how many retries or resume the download still fails.

**Screenshots**
![Screenshot_20240919_031602_Pix-EzViewer](https://github.com/user-attachments/assets/c48734e0-abec-47e2-9fc3-319b142f5e78)

**Smartphone (please complete the following information):**
 - Device: Galaxy S24
 - OS: Android 14
 - Browser: stock chrome.
 - Version: 1.8.8

**Comment by nnimoyoefoki** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by Trung0246** [comment]
> I think this will help you. https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw I put the necessary dlls in the archive

Not relevant? This is an Android project.

**Comment by Trung0246** [comment]
Update to 2.0.0
