### ISSUE TITLE
图片命名中的标签命名建议

### ISSUE THREAD

**Issue by LZTSGS** [ultranity/Pix-EzViewer#9]
有的标签很长也没什么用，写到图片名称里太浪费位置了，如果可以加入屏蔽带有关键词的标签写入图片名称的话，才可以在有限的命名空间里命名出最实用的标签嘛。
比如把“users入り”作为屏蔽关键词就能节省很多命名空间

**Comment by ultranity** [comment]
标签策略现在正在调整，之后会尽量避免重复以及短标签优先，下个版本可以体验下
