### ISSUE TITLE
2.0版本 无法查看作品评论

### ISSUE THREAD

**Issue by kaikai-toast** [ultranity/Pix-EzViewer#90]
**问题描述**
查看作品评论时会闪退
**如何复现**
查看作品评论

**正常&异常表现**

**BugReport**
可能的话附上截屏、logs 等信息

**环境说明**
 - 设备: HUAWEI Mate40 Pro
 - 系统: HarnonyOs 4.2.0
 - 软件版本 2.0.0

**附加**
在此处添加其他有关的任何内容。

![Screenshot_20241014_002214_com perol asdpl play pixivez](https://github.com/user-attachments/assets/e2462f11-ee72-48e3-9ff3-2be5805d6de4)

**Comment by kaikai-toast** [comment]
现在再次点进去看评论会直接跳到首页

**Comment by ultranity** [comment]
> 现在再次点进去看评论会直接跳到首页

新版本修复
