### ISSUE TITLE
固定导航栏底部出现多余的色块

### ISSUE THREAD

**Issue by blblfs** [ultranity/Pix-EzViewer#91]
**问题描述**
当我使用导航栏时，在导航栏会出现显眼的蓝色色块，且不会随动态色彩改变。

**如何复现**
使用导航栏进入应用出现

**正常&异常表现**
应当导航栏为透明状态，或隐藏导航栏

**BugReport**
![Screenshot_2024-12-03-11-54-26-795_com.perol.asdpl.play.pixivez.jpg](https://github.com/user-attachments/assets/385735b0-b248-4f14-b1d1-7db529ab3dcb)

**环境说明**
 - 设备: [xiaomi civi4 pro]
 - 系统: [hyperos1.0.17.0.UNJCNXM]
 - 软件版本 [2.0]

**附加**
无

**Comment by ultranity** [comment]
更新看看

**Comment by blblfs** [comment]
已修复![Screenshot_2024-12-06-08-20-50-602_com.perol.asdpl.play.pixivez.jpg](https://github.com/user-attachments/assets/ce6cf57b-29ea-474b-a929-500a71239bd0)
