### ISSUE TITLE
首页推荐显示问题

### ISSUE THREAD

**Issue by huajideshutiao** [ultranity/Pix-EzViewer#92]
**问题描述**
如图，好大的miku
插画链接 https://www.pixiv.net/artworks/124859659
![Screenshot_2024-12-06-02-02-22-371_com perol asdpl play pixivez](https://github.com/user-attachments/assets/4b41c609-a51e-4fce-aae5-750806db72f3)

**如何复现**
睡一觉就这样了

**正常&异常表现**
四分之一大小差不多

**BugReport**
可能的话附上截屏、logs 等信息

**环境说明**
 - 设备: [redmi k70 pro]
 - 系统: [Android 15]
 - 软件版本 [2.1.0]

**Comment by ultranity** [comment]
这种情况应该是这幅图片分辨率是横屏的触发了全图预览，但是加载的预览图是低分辨率的居中截图

我想想怎么处理更流畅一些
