### ISSUE TITLE
Can not import the exported download.log

### ISSUE THREAD

**Issue by GHolk** [ultranity/Pix-EzViewer#94]
**问题描述**

下载进度页面里的导入功能无法运作。
我导入 8 位数作品 id 正常，但 9 位数就无法导入。
但我看 regexp 是 `\d{7,9}` 应该能贪婪匹配到 9 位数才对？

https://github.com/ultranity/Pix-EzViewer/blob/bcbdccb91d505edef35a0f77ba8d810dd32c69cb/app/src/main/java/com/perol/asdpl/pixivez/ui/manager/DownloadManagerActivity.kt#L242

另外 254 行用 FileUtil.isDownloaded 可能有问题，
因为一个 pid 会有多张图片，一张存在不代表其他也存在？

**环境说明**

 - 软件版本 1.8.8

**Comment by ultranity** [comment]
更新下版本，新版本有支持更多导入导出信息
